name: generics
description: a pipeline that does arbitrary calculations using our generic arithmetic builtins
tags:
initialize:
  plugins:
    "sum":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - cpu/energy
          - network/energy
        output-parameter: energy-sum
    "coefficient":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: energy
        coefficient: 2
        output-parameter: energy-doubled
    "multiply":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["cpu/utilization", "duration"]
        output-parameter: "cpu-times-duration"
tree:
  children:
    child-1:
      pipeline:
        - sum
        - coefficient
        - multiply
      config:
      defaults:
        cpu/thermal-design-power: 100
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          cloud/instance-type: A1
          cloud/region: uk-west
          duration: 1
          cpu/utilization: 50
          cpu/energy: 20
          network/energy: 10
          energy: 5
