name: pipeline-with-mocks
description: a full pipeline seeded with data from mock-observations feature
tags:
aggregation:
  metrics:
    "carbon":
      method: sum
  type: "both"
initialize:
  plugins:
    mock-observations:
      kind: plugin
      method: MockObservations
      path: "builtin"
      global-config:
        timestamp-from: 2023-12-12T00:00
        timestamp-to: 2023-12-12T00:10
        duration: 60
        components:
          - cloud/instance-type: A1
        generators:
          common:
            cloud/region: uk-west
          randint:
            cpu/utilization:
              min: 1
              max: 99
      parameter-metadata:
        inputs:
          timestamp:
            description: refers to the time of occurrence of the input
            unit: RFC3339
            aggregationMethod: none
          duration:
            description: refers to the duration of the input
            unit: seconds
            aggregationMethod: sum
          cloud/instance-type:
            description: type of Cloud Instance name used in the cloud provider APIs
            unit: none
            aggregationMethod: none
          cloud/region:
            description: region cloud instance
            unit: none
            aggregationMethod: none
    "interpolate":
      method: Interpolation
      path: "builtin"
      global-config:
        method: linear
        x: [0, 10, 50, 100]
        y: [0.12, 0.32, 0.75, 1.02]
        input-parameter: "cpu/utilization"
        output-parameter: "cpu-factor"
      parameter-metadata:
        inputs:
          cpu/utilization:
            description: refers to CPU utilization.
            unit: percentage
            aggregationMethod: avg
        outputs:
          cpu-factor:
            description: result of interpolate
            unit: kWh
            aggregationMethod: avg
    "cpu-factor-to-wattage":
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["cpu-factor", "cpu/thermal-design-power"]
        output-parameter: "cpu-wattage"
      parameter-metadata:
        inputs:
          cpu/thermal-design-power:
            description: thermal design power for a processor
            unit: kwh
            aggregationMethod: avg
        outputs:
          cpu-wattage:
            description: the energy used by the CPU
            unit: kwh
            aggregationMethod: sum
    "wattage-times-duration":
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["cpu-wattage", "duration"]
        output-parameter: "cpu-wattage-times-duration"
    "wattage-to-energy-kwh":
      method: Divide
      path: "builtin"
      global-config:
        numerator: cpu-wattage-times-duration
        denominator: 3600000
        output: cpu-energy-raw
    "calculate-vcpu-ratio":
      method: Divide
      path: "builtin"
      global-config:
        numerator: vcpus-total
        denominator: vcpus-allocated
        output: vcpu-ratio
      parameter-metadata:
        inputs:
          vcpus-total:
            description: total number of vcpus available on a particular resource
            unit: count
            aggregationMethod: none
          vcpus-allocated:
            description: number of vcpus allocated to particular resource
            unit: count
            aggregationMethod: none
    "correct-cpu-energy-for-vcpu-ratio":
      method: Divide
      path: "builtin"
      global-config:
        numerator: cpu-energy-raw
        denominator: vcpu-ratio
        output: cpu-energy-kwh
    "sci-embodied":
      path: "builtin"
      method: SciEmbodied
    "operational-carbon":
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["cpu-energy-kwh", "grid/carbon-intensity"]
        output-parameter: "carbon-operational"
      parameter-metadata:
        inputs:
          grid/carbon-intensity:
            description: Carbon intensity for the grid
            unit: gCO2eq/kWh
            aggregationMethod: avg
    "sum-carbon":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - carbon-operational
          - carbon-embodied
        output-parameter: carbon
    "sci":
      path: "builtin"
      method: Sci
      global-config:
        functional-unit: "requests"
      parameter-metadata:
        inputs:
          requests:
            description: expressed the final SCI value
            unit: none
            aggregationMethod: sum
    "time-sync":
      method: TimeSync
      path: "builtin"
      global-config:
        start-time: "2023-12-12T00:00:00.000Z"
        end-time: "2023-12-12T00:01:00.000Z"
        interval: 5
        allow-padding: true
      parameter-metadata:
        inputs:
          time-reserved:
            description: time reserved for a component
            unit: seconds
            aggregationMethod: avg
    "group-by":
      path: builtin
      method: GroupBy
tree:
  children:
    child-1:
      pipeline:
        - mock-observations
        - interpolate
        - cpu-factor-to-wattage
        - wattage-times-duration
        - wattage-to-energy-kwh
        - calculate-vcpu-ratio
        - correct-cpu-energy-for-vcpu-ratio
        - sci-embodied
        - operational-carbon
        - sum-carbon
        - time-sync
        - sci
      config:
        group-by:
          group:
            - cloud/region
            - instance-type
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        vcpus-total: 8
        vcpus-allocated: 1
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          cloud/instance-type: A1
          cloud/region: uk-west
          duration: 1
          cpu/utilization: 10
          requests: 30
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          cpu/utilization: 20
          cloud/instance-type: A1
          cloud/region: uk-west
          requests: 40
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          cpu/utilization: 15
          cloud/instance-type: A1
          cloud/region: uk-west
          requests: 30
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          cloud/instance-type: A1
          cloud/region: uk-west
          cpu/utilization: 15
          requests: 50
    child-2:
      pipeline:
        - mock-observations
        - interpolate
        - cpu-factor-to-wattage
        - wattage-times-duration
        - wattage-to-energy-kwh
        - calculate-vcpu-ratio
        - correct-cpu-energy-for-vcpu-ratio
        - sci-embodied
        - operational-carbon
        - sum-carbon
        - time-sync
        - sci
      config:
        group-by:
          group:
            - cloud/region
            - cloud/instance-type
      defaults:
        cpu/thermal-design-power: 100
        grid/carbon-intensity: 800
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        vcpus-total: 8
        vcpus-allocated: 1
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          cpu/utilization: 30
          cloud/instance-type: A1
          cloud/region: uk-west
          requests: 30
        - timestamp: "2023-12-12T00:00:01.000Z"
          duration: 5
          cpu/utilization: 28
          cloud/instance-type: A1
          cloud/region: uk-west
          requests: 40
        - timestamp: "2023-12-12T00:00:06.000Z"
          duration: 7
          cpu/utilization: 40
          cloud/instance-type: A1
          cloud/region: uk-west
          requests: 50
        - timestamp: "2023-12-12T00:00:13.000Z"
          duration: 30
          cpu/utilization: 33
          cloud/instance-type: A1
          cloud/region: uk-west
          requests: 60
