name: regroup demo
description:
initialize:
  plugins:
    interpolate:
      method: Interpolation
      path: "builtin"
      config:
        method: linear
        x: [0, 10, 50, 100]
        y: [0.12, 0.32, 0.75, 1.02]
        input-parameter: "cpu/utilization"
        output-parameter: "cpu-factor"
tree:
  children:
    child:
      pipeline:
        observe:
        regroup:
          - cloud/region
          - cloud/instance-type
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 300
          cloud/instance-type: A1
          cloud/region: uk-west
          cpu/utilization: 99
        - timestamp: 2023-07-06T05:00
          duration: 300
          cloud/instance-type: A1
          cloud/region: uk-west
          cpu/utilization: 23
        - timestamp: 2023-07-06T10:00
          duration: 300
          cloud/instance-type: A1
          cloud/region: uk-west
          cpu/utilization: 12
        - timestamp: 2023-07-06T00:00 # note this time restarts at the start timstamp
          duration: 300
          cloud/instance-type: B1
          cloud/region: uk-west
          cpu/utilization: 11
        - timestamp: 2023-07-06T05:00
          duration: 300
          cloud/instance-type: B1
          cloud/region: uk-west
          cpu/utilization: 67
        - timestamp: 2023-07-06T10:00
          duration: 300
          cloud/instance-type: B1
          cloud/region: uk-west
          cpu/utilization: 1
