name: copy-param
description:
tags:
initialize:
  plugins:
    copy-param:
      path: builtin
      method: Copy
      global-config:
        keep-existing: true
        from: original
        to: copy
tree:
  children:
    child-1:
      pipeline:
        - copy-param
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          original: 'hello'
