name: mock-cpu-util-to-carbon
description: a complete pipeline that starts with mocked CPU utilization data and outputs operational carbon in gCO2eq
initialize:
  #outputs: ['yaml']
  plugins: 
    group-by: 
      path: 'builtin'
      method: GroupBy   
    operational-carbon:
      path: 'builtin'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'grid/carbon-intensity']
        output-parameter: 'carbon'       
    watttime:
      path: '@grnsft/if-unofficial-plugins'           
      method: WattTimeGridEmissions    
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline  
    cloud-metadata:
      path: builtin
      method: CSVLookup
      global-config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-azure-instances.csv
        query:
          instance-class: cloud/instance-type
        output: ['cpu-cores-utilized', 'vcpus-allocated']
    mock-observations:
      path: 'builtin'
      method: MockObservations
      global-config:
        timestamp-from: '2024-03-05T00:00:00.000Z'
        timestamp-to: '2024-03-05T00:01:00.000Z'
        duration: 10
        components:
          - name: server-1
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
          - name: server-2
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3            
        generators:
          common:
            cloud/vendor: azure
          randint:
            cpu/utilization:
              min: 1
              max: 99           
    'time-sync':
      method: TimeSync
      path: "builtin"
      global-config: 
        start-time: '2024-03-05T00:00:00.000Z'
        end-time: '2024-03-05T00:01:00.000Z'
        interval: 5
        allow-padding: true
tree: 
  pipeline:
    - mock-observations
    - group-by
    - time-sync
    - cloud-metadata
    - watttime
    - teads-curve
    - operational-carbon
  defaults:
  config:
    group-by:
      group:
        - cloud/region
        - name
  inputs: null
