name: csv-demo
description:
tags:
initialize:
  plugins:
    cloud-region-metadata:
      method: CSVLookup
      path: "builtin"
      global-config:
        filepath: https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/region-metadata.csv
        query:
          cloud-provider: cloud-provider 
          cloud-region: cloud-region
        output: "*"
tree:
  children:
    child:
      pipeline:
        - cloud-region-metadata
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.001
          instance-id: AMD A10-9700
          cloud-provider: "Google Cloud"
          cloud-region: "asia-east1"
