name: initialize-error-no-path
description: a negative test case that fails because the path is mising in a plugin initialization
tags:
initialize:
  plugins:
    teads-curve: 
      path:
      method: TeadsCurve
      global-config:
        interpolation: spline
  outputs: ['yaml']
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        - teads-curve
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          cpu/utilization: 20
        - timestamp: 2023-07-06T00:01
          duration: 1
          cpu/utilization: 80
        - timestamp: 2023-07-06T00:02
          duration: 1
          cpu/utilization: 20
