name: Aggregation
description: Apply both `horizontal` and `vertical` aggregations
aggregation:
  metrics:
    - 'test'
  type: 'both'
initialize:
  plugins:
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"              
tree:
  children:
    application:
      pipeline:
        - cloud-metadata
      children:
        uk-west:
          children:
            server-1:
              inputs:
                - timestamp: '2024-02-26 00:00:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 89
                - timestamp: '2024-02-26 00:05:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 59
            server-2:
              inputs:
                - timestamp: '2024-02-26 00:00:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 24
                - timestamp: '2024-02-26 00:05:00'
                  duration: 300
                  cloud/instance-type: m5n.large
                  cloud/vendor: aws
                  cpu/utilization: 27
