name: subtract demo
description:
tags:
initialize:
  plugins:
    subtract:
      method: Subtract
      path: "builtin"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy/diff"
tree:
  children:
    child:
      pipeline:
        - subtract
      config:
        subtract:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/energy: 0.003
          network/energy: 0.001
