name: divide-demo
description:
tags:
initialize:
  plugins:
    cloud-metadata:
      path: builtin
      method: CSVLookup
      global-config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-aws-instances.csv
        query:
          instance-class: cloud/instance-type
        output: ['cpu-cores-utilized', 'vcpus-allocated']
    divide:
      method: Divide
      path: "builtin"
      global-config:
        numerator: vcpus-allocated
        denominator: 2
        output: cpu/number-cores
    boavizta-cpu:
      method: BoaviztaCpuOutput
      path: "@grnsft/if-unofficial-plugins"
      global-config:
        allocation: LINEAR
        verbose: true
tree:
  children:
    child:
      pipeline:
        - cloud-metadata
        - divide
        - boavizta-cpu
      config:
        divide:
      defaults:
        cloud/vendor: aws
        cloud/instance-type: m5n.large
        cpu/name: Intel® Core™ i7-1185G7
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu/utilization: 80
