name: multiply
description: failure `inputs` is missing `cpu/energy` parameter
tags:
initialize:
  outputs: ['yaml']
  plugins:
    multiply:
      method: Multiply
      path: "builtin"
      global-config:
        input-parameters: ["cpu/energy", "network/energy"]
        output-parameter: "energy-product"
tree:
  children:
    child:
      pipeline:
        - multiply
      config:
        sum:
      inputs:
        - timestamp: 2023-08-06T00:00
          duration: 3600
          cpu: 0.001
          network/energy: 0.002
